keys:
  - &server DBF39C1CFAC86760C31C66F216748B49774F7A49
  - &local 4AB0D407666087F0106B49527683872A63E7531E
creation_rules:

  - path_regex: .*/server/.*
    pgp: *server

  - path_regex: .*/local/.*
    pgp: *local

  - key_groups:
    - pgp:
      - *server
      - *local
