# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!
{fetchNuGet}: [
  (fetchNuGet {
    pname = "Jellyfin.Common";
    version = "10.8.4";
    sha256 = "1hi112yy1hg31cppikhs8jbkx2f5ykbd1s91nmcp6lhy3k1b8x49";
  })
  (fetchNuGet {
    pname = "Jellyfin.Controller";
    version = "10.8.4";
    sha256 = "1c3wxkc27xlw8cyc4wqw9kvpvcmsqaibc7k7apmrl68i07wx2jzz";
  })
  (fetchNuGet {
    pname = "Jellyfin.Data";
    version = "10.8.4";
    sha256 = "1pw0bb072v0z1xjwva7xyl84vbh1yk1q7ipdmm4z5bby3gffprn9";
  })
  (fetchNuGet {
    pname = "Jellyfin.Extensions";
    version = "10.8.4";
    sha256 = "09r2pyskl9sgrdlcc2v0wv3vcr3l5vknlm5p5anvm55121pz98p8";
  })
  (fetchNuGet {
    pname = "Jellyfin.Model";
    version = "10.8.4";
    sha256 = "1q00zn3yxj8kbfzm1bkf01svhmbky52666slbnkdxg6h7nhybmgx";
  })
  (fetchNuGet {
    pname = "Jellyfin.Naming";
    version = "10.8.4";
    sha256 = "106vkl6knz801v2h1f8llzx6lfrls3b8cg1kdhq5safn7v01vq0s";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Abstractions";
    version = "6.0.0";
    sha256 = "0w6wwxv12nbc3sghvr68847wc9skkdgsicrz3fx4chgng1i3xy0j";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Binder";
    version = "6.0.0";
    sha256 = "15hb2rbzgri1fq8wpj4ll7czm3rxqzszs02phnhjnncp90m5rmpc";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection";
    version = "6.0.0";
    sha256 = "1wlhb2vygzfdjbdzy7waxblmrx0q3pdcqvpapnpmq9fcx5m8r6w1";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection";
    version = "6.0.2-mauipre.1.22102.15";
    sha256 = "13q4qgbqihvlgxni5n0ily9cq0ck9ncra3197zyzy8jv6f61avf2";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "6.0.0";
    sha256 = "1vi67fw7q99gj7jd64gnnfr4d2c0ijpva7g9prps48ja6g91x6a9";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "6.0.2-mauipre.1.22102.15";
    sha256 = "0p812hcd5his6vlwvp0sami7j7ipg0zdnij9hawbb118pimssxda";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Http";
    version = "6.0.2-mauipre.1.22102.15";
    sha256 = "19kk95k91djw0vba4ayxv8k37i1vn3xxd7vxinp4dxhlij0j48gm";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging";
    version = "6.0.0";
    sha256 = "0fd9jii3y3irfcwlsiww1y9npjgabzarh33rn566wpcz24lijszi";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging";
    version = "6.0.2-mauipre.1.22102.15";
    sha256 = "0k8qad47wvkf2v9m98qxdx2ffl33mcyp20g4rn9m5i69m7wgnl2x";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "6.0.1";
    sha256 = "17w4x7iakwpn7crg4yk5qkkv5gkx0lfl6anwwhb1554pwak5cwdz";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "6.0.2-mauipre.1.22102.15";
    sha256 = "0lzh34w4776nd7mlva97258jqpjf7x3ng53y6bh4wmalp8vm0csf";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options";
    version = "6.0.0";
    sha256 = "008pnk2p50i594ahz308v81a41mbjz9mwcarqhmrjpl2d20c868g";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options";
    version = "6.0.2-mauipre.1.22102.15";
    sha256 = "11kbv74dxd04j0x2y942g3ck75y9r34nnbl65d6118m816zdj9bk";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Primitives";
    version = "6.0.0";
    sha256 = "1kjiw6s4yfz9gm7mx3wkhp06ghnbs95icj9hi505shz9rjrg42q2";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Primitives";
    version = "6.0.2-mauipre.1.22102.15";
    sha256 = "1g7aj9ms77ax0m5739kg92d6yr3c47dif5yav8pyqy2lhqdm925p";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "1.1.0";
    sha256 = "08vh1r12g6ykjygq5d3vq09zylgb84l63k49jc4v8faw9g93iqqm";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Targets";
    version = "1.1.0";
    sha256 = "193xwf33fbm0ni3idxzbr5fdq3i2dlfgihsac9jj7whj0gd902nh";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Globalization";
    version = "4.3.0";
    sha256 = "1daqf33hssad94lamzg01y49xwndy2q97i2lrb7mgn28656qia1x";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Runtime";
    version = "4.3.0";
    sha256 = "1cqh1sv3h5j7ixyb7axxbdkqx6cxy00p4np4j91kpm492rf4s25b";
  })
  (fetchNuGet {
    pname = "runtime.native.System";
    version = "4.3.0";
    sha256 = "15hgf6zaq9b8br2wi1i3x0zvmk410nlmsmva9p0bbg73v6hml5k4";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Private.Uri";
    version = "4.3.0";
    sha256 = "1jx02q6kiwlvfksq1q9qr17fj78y5v6mwsszav4qcz9z25d5g6vk";
  })
  (fetchNuGet {
    pname = "SharpCompress";
    version = "0.32.2";
    sha256 = "1p198bl08ia89rf4n6yjpacj3yrz6s574snsfl40l8vlqcdrc1pm";
  })
  (fetchNuGet {
    pname = "StyleCop.Analyzers";
    version = "1.1.118";
    sha256 = "0hj4ax64cay2lvrh9693m0g4pmis0fi5wpm12xwzvc7lkizvac0a";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.DiagnosticSource";
    version = "6.0.0";
    sha256 = "0rrihs9lnb1h6x4h0hn6kgfnh58qq7hx8qq99gh6fayx4dcnx3s5";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.DiagnosticSource";
    version = "6.0.2-mauipre.1.22102.15";
    sha256 = "14zmx4awb4ggg3ld7ffac2ijsvhwl5ap2a29f2ncg5rwhlz2m20y";
  })
  (fetchNuGet {
    pname = "System.Globalization";
    version = "4.3.0";
    sha256 = "1cp68vv683n6ic2zqh2s1fn4c2sd87g5hpp6l4d4nj4536jz98ki";
  })
  (fetchNuGet {
    pname = "System.Private.Uri";
    version = "4.3.0";
    sha256 = "04r1lkdnsznin0fj4ya1zikxiqr0h6r6a1ww2dsm60gqhdrf0mvx";
  })
  (fetchNuGet {
    pname = "System.Runtime";
    version = "4.3.0";
    sha256 = "066ixvgbf2c929kgknshcxqj6539ax7b9m570cp8n179cpfkapz7";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "6.0.0";
    sha256 = "0qm741kh4rh57wky16sq4m0v05fxmkjjr87krycf5vp9f0zbahbc";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "6.0.2-mauipre.1.22102.15";
    sha256 = "144i90aj7fsnr4clhnl1qpd9jhnq83v35nj5gqa05hfgw900w18q";
  })
  (fetchNuGet {
    pname = "System.Text.Encodings.Web";
    version = "6.0.0";
    sha256 = "06n9ql3fmhpjl32g3492sj181zjml5dlcc5l76xq2h38c4f87sai";
  })
  (fetchNuGet {
    pname = "System.Text.Json";
    version = "6.0.5";
    sha256 = "12fg196sdq3gcjcz365kypfkkmdrprpcw2fvjnww9jqa4yn8v99l";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Dataflow";
    version = "6.0.0";
    sha256 = "1b4vyjdir9kdkiv2fqqm4f76h0df68k8gcd7jb2b38zgr2vpnk3c";
  })
]
